init script work in progress

diff --git a/steamcmd/templates/default/csgo.erb b/steamcmd/templates/default/csgo.erb
--- a/steamcmd/templates/default/csgo.erb
+++ b/steamcmd/templates/default/csgo.erb
@@ -1,103 +1,94 @@
 #!/bin/sh
 #
-# csgo Counter-Strike: Global Offensive server
+# Source Dedicated Server Init Script
 #
-# chkconfig:   <default runlevel(s)> <start> <stop>
-# description: <description, split multiple lines with \
-#              a backslash>
+# chkconfig: 345 99 01
+# description: some startup script
+#
 
-### BEGIN INIT INFO
-# Provides:
-# Required-Start:
-# Required-Stop:
-# Should-Start:
-# Should-Stop:
-# Default-Start:
-# Default-Stop:
-# Short-Description:
-# Description:
-### END INIT INFO
+# Server options
+TITLE='Source Dedicated Server'   # Script initialization title
+LONGNAME='Counter-Strike: GO'     # Full title of game type
+NAME='csgo'                       # Server handle for the screen session
+DAEMON='srcds_run'                # The server daemon
+STEAM='/opt/steamcmd/apps/csgo'   # STEAM to Steam installation
+USER='steam'
 
-# Source function library.
-. /etc/rc.d/init.d/functions
+# Game options
+IP='0.0.0.0'                      # IP of the server
+PORT='27015'                      # Port number to
+MAP='de_dust2'                    # Initial map to start
+GAME='csgo'                       # Game type (tf|cstrike|valve|hl2mp|csgo)
+SIZE='24'                         # Maximum number of players
 
-exec="/opt/steamcmd/apps/csgo/srcds_run"
-prog="csgo"
-#config=""
+# Server options string
+OPTS="-game $GAME +hostname \"$CLIENT\" +map $MAP +ip $IP -port $PORT \
+    -autoupdate +maxplayers $SIZE -pidfile $STEAM/$GAME/$NAME.pid"
 
-lockfile=/var/lock/subsys/$prog
+# Screen command
+INTERFACE="/usr/bin/screen -A -m -d -S $NAME"
 
-start() {
-    [ -x $exec ] || exit 5
-    #[ -f $config ] || exit 6
-    echo -n $"Starting $prog: "
-    #su - steam -c "cd /opt/steamcmd/apps/csgo && $exec -game csgo -console -usercon +game_type 0 +game_mode 0 +mapgroup mg_active +map de_dust2"
-    daemon --user=steam cd /opt/steamcmd/apps/csgo && $exec -game csgo -console -usercon +game_type 0 +game_mode 0 +mapgroup mg_active +map de_dust2 &>/dev/null &
-    retval=$?
-    echo
-    [ $retval -eq 0 ] && touch $lockfile
-    return $retval
+service_start() {
+    # Check if the pid files currently exist
+    if [ ! -f $STEAM/$GAME/$NAME.pid ] && [ ! -f $STEAM/$GAME/$NAME-screen.pid ]; then
+        if [ -x $STEAM/$DAEMON ]; then
+            echo "Starting $TITLE - $LONGNAME"
+            echo "Server IP: $IP"
+            echo "Server port: $PORT"
+            echo "Server size: $SIZE players"
+            cd $STEAM
+            $INTERFACE $STEAM/$DAEMON $OPTS
+            # Prevent race condition on SMP kernels
+            sleep 1
+            # Find and write current process id of the screen process
+            ps -ef | grep SCREEN | grep "$NAME" | grep -v grep | awk '{ print $2 }' > $STEAM/$GAME/$NAME-screen.pid
+            echo "$TITLE screen process ID written to $STEAM/$GAME/$NAME-screen.pid"
+            echo "$TITLE server process ID written to $STEAM/$GAME/$NAME.pid"
+
+            echo "$TITLE started."
+        fi
+    else
+        echo -e "Cannot start $TITLE.  Server is already running."
+        #exit 1
+    fi
 }
 
-stop() {
-    echo -n $"Stopping $prog: "
-    killproc $prog
-    retval=$?
-    echo
-    [ $retval -eq 0 ] && rm -f $lockfile
-    return $retval
+service_stop() {
+    if [ -f $STEAM/$GAME/$NAME.pid ] && [ -f $STEAM/$GAME/$NAME-screen.pid ]; then
+        echo "Stopping $TITLE - $LONGNAME."
+        # Get the process ID from the pid file we created earlier
+        for id in `cat $STEAM/$GAME/$NAME-screen.pid`
+            do kill -9 $id
+            echo "Killing process ID $id"
+            echo "Removing $TITLE screen pid file"
+            rm -rf $STEAM/$GAME/$NAME-screen.pid
+            break
+        done
+        # Remove server pid file
+        echo "Removing $TITLE pid file"
+        rm -rf $STEAM/$GAME/$NAME.pid
+        # Wipe all old screen sessions
+        screen -wipe 1> /dev/null 2> /dev/null
+        echo "$TITLE stopped."
+    else
+        echo -e "Cannot stop $TITLE.  Server is not running."
+        #exit 1
+    fi
 }
 
-restart() {
-    stop
-    start
-}
-
-reload() {
-    restart
-}
-
-force_reload() {
-    restart
-}
-
-rh_status() {
-    # run checks to determine if the service is running or use generic status
-    status $prog
-}
-
-rh_status_q() {
-    rh_status >/dev/null 2>&1
-}
 
 case "$1" in
-    start)
-        rh_status_q && exit 0
-        $1
+    'start')
+        service_start
         ;;
-    stop)
-        rh_status_q || exit 0
-        $1
+    'stop')
+        service_stop
         ;;
-    restart)
-        $1
-        ;;
-    reload)
-        rh_status_q || exit 7
-        $1
-        ;;
-    force-reload)
-        force_reload
-        ;;
-    status)
-        rh_status
-        ;;
-    condrestart|try-restart)
-        rh_status_q || exit 0
-        restart
+    'restart')
+        service_stop
+        sleep 1
+        service_start
         ;;
     *)
-        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
-        exit 2
+        echo "Usage $0 start|stop|restart"
 esac
-exit $?
